#!/bin/sh

xset s off
xset -dpms

if $(cat ~/ivy/data/config.json | jq 'has("client")'); then
        i3-msg "exec xterm -fg white -bg black -e python3.6 ~/ivy/display.py"
elif $(cat ~/ivy/data/config.json | jq 'has("master")'); then
        i3-msg "exec chromium-browser --app=http://localhost/"
else
        i3-msg "exec xterm -fg white -bg black"
fi
