#!/bin/sh

xset s off
xset -dpms

if $(cat /etc/ivy/config.json | jq 'has("client")'); then
        i3-msg "exec xterm -fg white -bg black -e python3.6 /opt/ivy/display.py"
elif $(cat /etc/ivy/config.json | jq 'has("relay")'); then
        i3-msg "exec chromium-browser --app=http://localhost/"
else
        i3-msg "exec xterm -fg white -bg black"
fi
